const fs=require("fs")
// fs.mkdirSync("jabeena")


// // create
// fs.writeFileSync("jabeena/bio.txt","i m jabeena")


// // append
// fs.appendFileSync("jabeena/bio.txt"," i m a student")


// // read
// const data=fs.readFileSync("jabeena/bio.txt","utf8")
// console.log(data)


// // rename
// fs.renameSync("jabeena/bio.txt","jabeena/mybio.txt")



// // delete
// fs.unlinkSync("jabeena/mybio.txt")